version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2013
configuration:
- Release
- Debug
platform:
- x64
- Win32 
clone_depth: 1
init:
- cmd: echo %Platform% %Configuration%
install:
- cmd: ensure_dependencies.py
before_build:
- cmd: createsolution.bat
- cmd: >-
    if "%Platform%"=="Win32" set arch="ia32"

    if "%Platform%"=="x64" set arch="x64"

build_script:
- cmd: msbuild "build/%arch%/libadblockplus.sln" /m /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test_script:
- cmd: build\%arch%\build\%Configuration%\tests.exe --gtest_output=xml:tests.xml
after_test:
- ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\tests.xml))
deploy: off
